version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - my-app-network

  nestjs-app:
    build: .
    container_name: my-nestjs-app
    restart: on-failure
    ports:
      - "${PORT}:4000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
      TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
      TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
      CRYPT_SALT: ${CRYPT_SALT}
      TEST_MODE: auth

    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres-db
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge

volumes:
  db-data:
